spring:
  application:
    name: api-sms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8086}